version: '3'

services:
  db:
    image: postgres:15
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cruds
      - POSTGRES_USER=cruds
      - POSTGRES_PASSWORD=test
